### ISSUE TITLE
Do not redirect to sgmap.github.io on missing trailing slashes

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#734]
Probably due to redirect/baseurl. Relates to #730 

<img width="1353" alt="capture d ecran 2017-05-31 a 12 33 39" src="https://cloud.githubusercontent.com/assets/329236/26628207/77f36a58-45fd-11e7-82a5-dd4c609acf83.png">

<img width="1440" alt="capture d ecran 2017-05-31 a 12 39 24" src="https://cloud.githubusercontent.com/assets/329236/26628393/3886190a-45fe-11e7-906e-2aed8c5a20f4.png">

http://browsershots.org/http://sgmap.github.io/beta.gouv.fr/en/

**Comment by MattiSG** [comment]
Can't reproduce. It's normal if you're on sgmap.github.io. This website is not intended to be seen on this root, but on beta.gouv.fr. It is quite a lot of work to support both.

**Comment by maukoquiroga** [comment]
Yep, thing is, I think, there was a CNAME redirection that must've beed addressed by now. @Morendil ?

**Comment by MattiSG** [comment]
If it was a CNAME then there's no reason that would happen only on a specific page.

**Comment by Morendil** [comment]
Apparently, @maukoquiroga was accessing the site via http(s?)://beta.gouv.fr/en/ so @MattiSG's hypothesis above does not apply.

On the CNAME: we do not use the normal CNAME mechanism of Github pages because we're keen on serving over HTTPS with our certificate, via nginx proxy. This does cause some problems.

What's odd is that @maukoquiroga seems to be experiencing this intermittently - failed earlier today, works now. I favor keeping it open for a short time to figure it out.

**Comment by Morendil** [comment]
Reproduced, but the triggering condition is to visit a "wrong" URL: beta.gouv.fr/en (no trailing slash).

**Comment by Morendil** [comment]
Je ne reproduis pas en local par contre.

**Comment by Morendil** [comment]
Est-ce que ça serait par hasard notre setup reverse proxy sur nginx qui serait incomplet ? Genre quand il reçoit un 301 de sgmap.github.io il le renvoie tel quel au lieu d'en faire un 301 sur beta.gouv.fr ? @jdesboeufs tu as une idée ?

**Comment by Morendil** [comment]
Effectivement l'ajout d'un `proxy_redirect` corrige le problème. (Pensez à vider votre cache navigateur si vous faites des tests pour vérifier la correction.)
